# Each route describes how an incoming URL will be processed by Platform.sh.
"https://{default}/":
  type: upstream
  upstream: "ll_project:http"
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

# Each service listed will be deployed in its own container as part of your
# Platform.sh project.
db:
 type: postgresql:12
 disk: 1024  